// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-7iwrncOijErpraj1tX6CAPRsNuaK0g',
    appId: '1:1018668404314:web:0185e87a7f04001b0a5263',
    messagingSenderId: '1018668404314',
    projectId: 'healthensure-4c0a8',
    authDomain: 'healthensure-4c0a8.firebaseapp.com',
    storageBucket: 'healthensure-4c0a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-2SF1Q0FS0s1QdIvmqrszMq20bFfzZA',
    appId: '1:1018668404314:android:6c5ce1922c580cc70a5263',
    messagingSenderId: '1018668404314',
    projectId: 'healthensure-4c0a8',
    storageBucket: 'healthensure-4c0a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxXPgjZtKHW7UKNZEr3iO0qWFA3ZEQNyE',
    appId: '1:1018668404314:ios:fb3e7fa16eec3d030a5263',
    messagingSenderId: '1018668404314',
    projectId: 'healthensure-4c0a8',
    storageBucket: 'healthensure-4c0a8.appspot.com',
    iosClientId:
        '1018668404314-48kh91dqlr2vadsh960u960nr7akbo2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthensure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxXPgjZtKHW7UKNZEr3iO0qWFA3ZEQNyE',
    appId: '1:1018668404314:ios:fb3e7fa16eec3d030a5263',
    messagingSenderId: '1018668404314',
    projectId: 'healthensure-4c0a8',
    storageBucket: 'healthensure-4c0a8.appspot.com',
    iosClientId:
        '1018668404314-48kh91dqlr2vadsh960u960nr7akbo2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthensure',
  );
}
